name: dmrtd
description: Dart implementation of ICAO Doc 9303 MRTD, created by ZeroPass

version: 1.1.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.1.2
  convert: ^3.0.0
  crypto: ^3.0.1
  fixnum: ^1.0.0
  flutter_nfc_kit: '^3.1.0'
  logging: ^1.0.1
  meta: ^1.3.0
  tripledes: ^2.1.0

dev_dependencies:
  flutter:      # needed for flutter_nfc_kit
    sdk: flutter
  flutter_test: # needed for flutter_nfc_kit
    sdk: flutter
  test: ^1.16.5