name: dmrtd
description: Dart implementation of ICAO Doc 9303 MRTD, created by ZeroPass

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  archive: ^3.1.2
  convert: ^3.0.0
  crypto: ^3.0.1
  flutter_nfc_kit: '1.1.0' # on iOS version >= 1.2 due to pollingOption with .iso18092 tag
                           # requires ISO18092 (felica) entry with proper system code in info.plist.
  logging: ^1.0.1
  meta: ^1.3.0
  tripledes: ^2.1.0

dev_dependencies:
  flutter:      # needed for flutter_nfc_kit
    sdk: flutter
  flutter_test: # needed for flutter_nfc_kit
    sdk: flutter
  test: ^1.16.5